SUPABASE_URL = "https://xwpwhrqyayniviaidkjz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cHdocnF5YXluaXZpYWlka2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDA2MTcsImV4cCI6MjA2MzgxNjYxN30.1Sk5hBtFRm2CMRKpXTAcYe0pChOTopVOZdyTt7mdgVw"
GROQ_API_KEY = "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"
